//! Known-answer tests for the hardened key schedule (backlog B2/B3): the domain
//! tree, the v3 gateway hashes and keyed chain, and the relay-v4 derivations.
//!
//! Expected values in `tests/vectors/kdf-domains.json`, `handshake-v3.json` and
//! `relay-v4.json` were generated by an independent implementation (Python
//! `hashlib` SHA3-256 + `hmac`) of the rules written in `docs/KEY-SCHEDULE.md`;
//! these tests assert the Rust code reproduces them byte for byte. A deliberate
//! change to any rule must publish a new vector set.

use pq_qkd_proxy::crypto::{client_hello_digest_v3, derive_v3_session_key, transcript_hash_v3};
use pq_qkd_proxy::kdf::{self, ALL_DOMAINS};
use pq_qkd_proxy::relay::{
    derive_directional_key, ratchet_step, relay_hello_digest, relay_transcript,
};
use serde_json::Value;

const DOMAINS: &str = include_str!("vectors/kdf-domains.json");
const V3: &str = include_str!("vectors/handshake-v3.json");
const RELAY: &str = include_str!("vectors/relay-v4.json");

fn hex_decode(s: &str) -> Vec<u8> {
    assert!(s.len().is_multiple_of(2), "odd-length hex");
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).expect("bad hex"))
        .collect()
}

fn hex_encode(b: &[u8]) -> String {
    b.iter().map(|x| format!("{:02x}", x)).collect()
}

fn pattern(len: usize, a: usize, b: usize) -> Vec<u8> {
    (0..len).map(|i| ((i * a + b) & 0xff) as u8).collect()
}

fn arr32(v: &[u8]) -> [u8; 32] {
    let mut out = [0u8; 32];
    out.copy_from_slice(v);
    out
}

fn input(v: &Value, key: &str) -> Vec<u8> {
    hex_decode(v["inputs"][key].as_str().expect(key))
}

fn expected<'a>(v: &'a Value, key: &str) -> &'a str {
    v["expected"][key].as_str().expect(key)
}

#[test]
fn every_domain_constant_matches_the_published_tree() {
    let v: Value = serde_json::from_str(DOMAINS).unwrap();
    assert_eq!(v["root"], "PQTG-DOMAIN-TREE-v1");
    let published = v["domains"].as_object().unwrap();
    assert_eq!(
        published.len(),
        ALL_DOMAINS.len(),
        "the published set and the registry must list the same domains"
    );
    for path in ALL_DOMAINS {
        let key = path.join("/");
        let want = published[&key]
            .as_str()
            .unwrap_or_else(|| panic!("{key} missing"));
        assert_eq!(hex_encode(&kdf::domain(path)), want, "domain {key}");
    }
    // And the statics used by the code are those constants.
    assert_eq!(
        hex_encode(&*kdf::GATEWAY_V3_SESSION_KEY),
        published["gateway/v3/session-key"].as_str().unwrap()
    );
    assert_eq!(
        hex_encode(&*kdf::RELAY_RATCHET),
        published["relay/v4/ratchet"].as_str().unwrap()
    );
}

#[test]
fn kat_v3_transcript_hello_and_session_keys() {
    let v: Value = serde_json::from_str(V3).unwrap();
    let cr = arr32(&input(&v, "client_random"));
    let sr = arr32(&input(&v, "server_random"));
    let ek = pattern(1184, 7, 3);
    let pk = pattern(897, 13, 5);
    let ct = pattern(1088, 11, 9);
    let ss = arr32(&input(&v, "kem_ss"));
    let qkd = input(&v, "qkd_key");
    let slh = input(&v, "slh_dsa_vk");

    let hyb = &v["inputs"]["hybrid"];
    let t_hybrid = transcript_hash_v3(
        &cr,
        &sr,
        &ek,
        &pk,
        &ct,
        hyb["key_mode_byte"].as_u64().unwrap() as u8,
        hyb["qkd_key_id"].as_str().unwrap().as_bytes(),
        hyb["master_sae_id"].as_str().unwrap().as_bytes(),
        hyb["qkd_key_len"].as_u64().unwrap() as u32,
    );
    assert_eq!(hex_encode(&t_hybrid), expected(&v, "transcript_hybrid"));

    let pqc = &v["inputs"]["pqc_only"];
    let t_pqc = transcript_hash_v3(
        &cr,
        &sr,
        &ek,
        &pk,
        &ct,
        pqc["key_mode_byte"].as_u64().unwrap() as u8,
        pqc["qkd_key_id"].as_str().unwrap().as_bytes(),
        pqc["master_sae_id"].as_str().unwrap().as_bytes(),
        pqc["qkd_key_len"].as_u64().unwrap() as u32,
    );
    assert_eq!(hex_encode(&t_pqc), expected(&v, "transcript_pqc_only"));

    let hello = client_hello_digest_v3(
        &cr,
        v["inputs"]["timestamp"].as_u64().unwrap(),
        &ek,
        &pk,
        &slh,
        v["inputs"]["requested_key_size"].as_u64().unwrap(),
        v["inputs"]["client_sae_id"].as_str().unwrap().as_bytes(),
        v["inputs"]["qkd_capable"].as_bool().unwrap(),
    );
    assert_eq!(hex_encode(&hello), expected(&v, "client_hello_digest"));

    assert_eq!(
        hex_encode(&derive_v3_session_key(&ss, None, &t_pqc)),
        expected(&v, "session_key_pqc_only")
    );
    assert_eq!(
        hex_encode(&derive_v3_session_key(&ss, Some(&qkd), &t_hybrid)),
        expected(&v, "session_key_hybrid")
    );
}

#[test]
fn kat_relay_v4_hello_transcript_keys_and_ratchet() {
    let v: Value = serde_json::from_str(RELAY).unwrap();
    let cr = arr32(&input(&v, "client_random"));
    let sr = arr32(&input(&v, "server_random"));
    let ek = pattern(1184, 7, 3);
    let ct = pattern(1088, 11, 9);
    let cvk = pattern(897, 17, 1);
    let svk = pattern(897, 13, 5);
    let slh = input(&v, "slh_dsa_vk");
    let ss = arr32(&input(&v, "kem_ss"));
    let ts = v["inputs"]["timestamp"].as_u64().unwrap();

    assert_eq!(
        hex_encode(&relay_hello_digest(&cr, ts, &ek, &cvk, &slh)),
        expected(&v, "hello_digest")
    );
    let t = relay_transcript(&cr, &sr, &ek, &ct, &cvk, &svk);
    assert_eq!(hex_encode(&t), expected(&v, "transcript"));

    let c2s = derive_directional_key(&ss, &t, &kdf::RELAY_KEY_C2S);
    let s2c = derive_directional_key(&ss, &t, &kdf::RELAY_KEY_S2C);
    assert_eq!(hex_encode(&c2s), expected(&v, "key_c2s"));
    assert_eq!(hex_encode(&s2c), expected(&v, "key_s2c"));
    assert_ne!(c2s, s2c);

    let r1 = ratchet_step(&c2s, 1, &[]);
    assert_eq!(
        hex_encode(&r1),
        expected(&v, "ratchet_epoch1_hash_only_from_c2s")
    );
    let r2 = ratchet_step(&r1, 2, &ss);
    assert_eq!(
        hex_encode(&r2),
        expected(&v, "ratchet_epoch2_with_fresh_kem_ss_from_epoch1")
    );
}
